TIME_REFRESH = 50
CANVAS_WIDTH = 801
CANVAS_HEIGHT = 601
CANVAS_BACKGROUND_COLOR = 'black'
GRID_WIDTH = 80
GRID_HEIGHT = 60
GRID_COLOR = 'blue'
SNAKE_INIT_LENGTH = 20
SNAKE_BODY_COLOR = 'yellow'
SNAKE_HEAD_COLOR = 'brown'
SNAKE_DEAD_COLOR = 'red'
FOOD_COLOR = 'green'


